CREATE TABLE plugin_data (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
	version INTEGER NOT NULL,
	aspect_type VARCHAR(24) NOT NULL,
	start_time BIGINT NOT NULL,
	end_time BIGINT NOT NULL,

	CONSTRAINT plugin_data_pk PRIMARY KEY(id)
);

-- create index on discriminator column
CREATE INDEX plugin_data_atype_idx ON plugin_data(aspect_type);

-- create index on start/end time since many queries will use it
CREATE INDEX plugin_data_stime_idx ON plugin_data(start_time);
CREATE INDEX plugin_data_etime_idx ON plugin_data(end_time);
CREATE INDEX plugin_data_duration_idx ON plugin_data(start_time,end_time);

-- Make sure same ID used in order to implement JOIN inheritence strategy
CREATE TABLE sql_stmt_plugin (
	id BIGINT NOT NULL,
	sql_stmt VARCHAR(2048) NOT NULL,

	CONSTRAINT sql_stmt_plugin_pk PRIMARY KEY(id),
	CONSTRAINT sql_plugin_data_fk FOREIGN KEY(id) REFERENCES plugin_data(id)
);
